server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gmall_study?useUnicode=true&characterEncoding=UTF-8&useSLL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: com.wang.user.entity